# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

g1_isaacgym:
  model_name: "policy.pt"
  framework: "isaacgym"
  rows: 2
  cols: 6
  dt: 0.002
  decimation: 10
  num_observations: 45
  observations: ["commands", "ang_vel", "gravity_vec", "dof_pos", "dof_vel", "actions"]
  observations_history: [9, 8, 7 ,6 ,5, 4, 3, 2, 1, 0]
  depth_height: 48
  depth_width: 64
  clip_obs: 100.0
  clip_actions_lower: [-100, -100, -100, -100, -100, -100,
                       -100, -100, -100, -100, -100, -100]
  clip_actions_upper: [100, 100, 100, 100, 100, 100, 
                       100, 100, 100, 100, 100, 100]
  rl_kp: [100, 100, 100, 150, 40, 40, 
          100, 100, 100, 150, 40, 40]
  rl_kd: [2, 2, 2, 4, 2, 2, 
          2, 2, 2, 4, 2, 2]
  torque_limits: [88, 139, 88, 139, 50, 50,
                  88, 139, 88, 139, 50, 50]
  default_dof_pos: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0, 
                    -0.1,  0.0,  0.0,  0.3, -0.2, 0.0]
  arm_waist_kp: [300, 300, 300,
                 100, 100, 50, 50, 20, 20, 20,
                 100, 100, 50, 50, 20, 20, 20]
  arm_waist_kd: [3, 3, 3, 
                 2, 2, 2, 2, 1, 1, 1,
                 2, 2, 2, 2, 1, 1, 1]
  arm_waist_target: [0, 0, 0,
                     0, 0.25, 0, 1.2, 0, 0, 0,
                     0, -0.25, 0, 1.2, 0, 0, 0]
  leg_joint2motor_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
  arm_waist_joint2motor_idx: [12, 13, 14, 
                              15, 16, 17, 18, 19, 20, 21, 
                              22, 23, 24, 25, 26, 27, 28]
  hip_scale_reduction: 1.0
  hip_scale_reduction_indices: []
  num_of_dofs: 12
  num_of_arm_waist_dofs: 17
  action_scale: 0.25
  action_scale_wheel: 0.0
  wheel_indices: []
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [2.0, 2.0, 0.25]
  max_command: [0.8, 0.0, 0.5]
  joint_controller_names: 
  ["left_hip_pitch_controller", "left_hip_roll_controller", "left_hip_yaw_controller", "left_knee_controller", "left_ankle_pitch_controller", "left_ankle_roll_controller",
  "right_hip_pitch_controller", "right_hip_roll_controller", "right_hip_yaw_controller", "right_knee_controller", "right_ankle_pitch_controller", "right_ankle_roll_controller"]

